name: all
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  residemenu: ^1.3.7
  convex_bottom_bar: ^3.0.0
  floating_bottom_navigation_bar: ^1.5.2
  curved_navigation_bar: ^1.0.3
  spincircle_bottom_bar: ^2.0.0
  intl: ^0.17.0
  flushbar: ^1.10.4
  carousel_slider: ^4.0.0
  marquee: ^2.2.2
  solid_bottom_sheet: ^0.1.10
  expandable_bottom_bar: ^2.0.2
  group_button: ^5.0.1
  dropdown_plus: ^0.0.9
  flutter_picker: ^2.0.3
  sliding_clipped_nav_bar: ^3.1.0+2
  animated_bottom_navigation_bar: ^1.0.1
  flutter_snake_navigationbar: ^0.6.1
  circular_reveal_animation: ^2.0.0
  bloc: ^8.0.3
  conditional_builder: ^1.0.2
  animated_text_kit: ^4.2.2
  animated_widgets: ^1.1.0
  dotted_border: ^2.0.0+2
  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  image_picker: ^0.8.5+3
  multi_image_picker: ^4.8.1
  splashscreen: ^1.3.5
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  flutter_local_notifications: ^9.7.0
  rxdart: ^0.27.5
  timezone: ^0.8.0
  circular_countdown_timer: ^0.2.2
  stop_watch_timer: ^1.5.0
  custom_timer: ^0.1.2
  slide_countdown: ^0.2.12
  flutter_timer_countdown: ^1.0.3
  flutter_native_timezone: ^2.0.0
  auto_size_text: ^3.0.0
  card_swiper: ^2.0.1
  auth_buttons: ^3.0.0
  like_button: ^2.0.4
  sign_button: ^2.0.2
  slider_button: ^2.0.0
  toggle_bar_button: ^1.0.1
  figma_squircle: ^0.5.3
  device_preview: ^1.1.0
  url_launcher: ^6.1.5
  mailer: ^3.2.1
  flutter_alarm_clock: ^0.0.2
  http: ^0.13.5
  timer_builder: ^2.0.0
  sidebarx: ^0.10.0
  side_navigation: ^1.0.2
  elastic_drawer: ^2.0.2
  drawerbehavior: ^2.2.2
  curved_drawer_fork: ^0.0.1+1
  flutter_inner_drawer: ^1.0.0+1
  awesome_drawer_bar: ^1.0.0
  flutter_zoom_drawer: ^3.0.3
  kf_drawer: ^1.2.1
  flutter_colorpicker: ^0.3.2
  select_dialog: ^2.0.0
  native_ios_dialog: ^0.0.2
  page_transition: ^2.0.5
  device_info: ^2.0.2
  image: ^3.0.8
  responsive_framework: ^0.2.0
  flutter_screenutil: ^5.0.0+2
  google_fonts: ^3.0.1
  webview_flutter: ^3.0.4
  readmore: ^2.1.0
  camera: ^0.10.0+1
  video_player: ^2.4.7
  flutter_neumorphic: ^3.2.0
  animated_neumorphic: ^0.2.0
  intl_phone_field: ^3.1.0
  rating_dialog: ^2.0.4
  in_app_review: 2.0.3
  percent_indicator: ^3.0.1
  argon_buttons_flutter: ^1.1.0
  flutter_spinkit: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/bg0.jpeg
    - assets/image/bg1.jpeg
    - assets/image/bg2.jpeg
    - assets/image/bg.jpeg
    - assets/image/1.png
    - assets/image/2.png
    - assets/image/3.png
    - assets/image/top_image.png
    - assets/image/mobile.png

  fonts:
    - family: IconFont
      fonts:
        - asset: assets/fonts/IconFont.ttf

